### ISSUE TITLE
IDX21323 Error after apply same site cookie in Chromo Rigorous mode

### ISSUE THREAD

**Issue by wangzhengdao** [aspnet/Announcements#410]
To be compatible with Chrome 80-  version,We have Implemented Same site Cookies for OWIN application with reference 
https://docs.microsoft.com/en-us/aspnet/samesite/owin-samesite
We have 
1.	upgrade owin to 4.1 
2.	Target .net framework to .net 4.7.2
It works  fine In Chrome V 80 Beta we do not have issue however, when in rigorous mode (.\chrome.exe --enable-features=SameSiteDefaultChecksMethodRigorously). it gives out the following error:
Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolInvalidNonceException: IDX21323: RequireNonce is '[PII is hidden]'. OpenIdConnectProtocolValidationContext.Nonce was null, OpenIdConnectProtocol.ValidatedIdToken.Payload.Nonce was not null. The nonce cannot be validated. If you don't need to check the nonce, set OpenIdConnectProtocolValidator.RequireNonce to 'false'. Note if a 'nonce' is found it will be evaluated.
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolValidator.ValidateNonce(OpenIdConnectProtocolValidationContext validationContext)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolValidator.ValidateAuthenticationResponse(OpenIdConnectProtocolValidationContext validationContext)
   at Microsoft.Owin.Security.OpenIdConnect.OpenIdConnectAuthenticationHandler.<AuthenticateCoreAsync>d__9.MoveNext()

**Comment by regisbsb** [comment]
Can we have a robot 🤖 that closes those issues and responds with it shouldn't be here?
