### ISSUE TITLE
Runtime refactoring in Beta7

### ISSUE THREAD

**Issue by anurse** [aspnet/Announcements#45]
DNX builds from the `aspnetvnext` feed (starting with `1.0.0-beta7-12264`) contain some changes that break older packages. If you encounter issues using a Beta7 DNX or Package, ensure your DNX and Packages are all up to date with the latest from the `aspnetvnext` feed.

I'll collect a set of known symptomatic error messages below. If you are seeing one of the below error messages, you're probably falling victim to this issue.

**Comment by anurse** [comment]
The following error indicates that you are using a version of `xunit.runner.dnx` that is not compatible with these changes. A pull request is out to update xunit to react to these changes: xunit/dnx.xunit#51. Until that PR is accepted, you will need to either revert your DNX and packages to an older known-good state, or consume `xunit.runner.dnx` as source via a project reference.

```
System.MissingMethodException: Method not found: 'System.Collections.Generic.IEnumerable`1<Microsoft.Framework.Runtime.ILibraryInformation> Microsoft.Framework.Runtime.ILibraryManager.GetReferencingLibraries(System.String)'.
   at Xunit.Runner.Dnx.Program.GetAvailableRunnerReporters()
   at Xunit.Runner.Dnx.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, FrameworkName targetFramework)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args, FrameworkName targetFramework)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args, FrameworkName targetFramework)
```

**Comment by anurse** [comment]
Compiler errors relating to any type that originates from `Microsoft.Framework.Runtime.Abstractions` indicate that you are impacted by this issue. The refactoring was focused on this package.

Also, some types have been moved from `Microsoft.Framework.Runtime.Abstractions` to `Microsoft.Framework.Runtime.Compilation.Abstractions`, specifically those relating to compilation (as indicated by our creative naming ;)). If a type appears to have vanished, it might be in this new package.

**Comment by CarlosFreire** [comment]
Please help

1>------ Rebuild All started: Project: Cross2Business.Comun, Configuration: Debug Any CPU ------
1>  C:\Users\carlos.freire\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta7-12264\bin\dnx.exe --appbase "C:\Canales\Cross2Business\PlataformaWeb\C2B\src\Cross2Business.Comun" "C:\Users\carlos.freire\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta7-12264\bin\lib\Microsoft.DNX.PackageManager\Microsoft.DNX.PackageManager.dll" pack "C:\Canales\Cross2Business\PlataformaWeb\C2B\src\Cross2Business.Comun" --configuration Debug --out "..\..\artifacts\bin\Cross2Business.Comun"
1>  System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DNX.PackageManager' or one of its dependencies. The system cannot find the file specified.
1>  File name: 'Microsoft.DNX.PackageManager'
1>     at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
1>     at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
1>     at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
1>     at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
1>     at Microsoft.Framework.Runtime.Loader.LoadContext.Load(AssemblyName assemblyName)
1>     at dnx.host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, FrameworkName targetFramework)
1>     at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args, FrameworkName targetFramework)
1>     at dnx.host.RuntimeBootstrapper.Execute(String[] args, FrameworkName targetFramework)
1>  WRN: Assembly binding logging is turned OFF.
1>  To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
1>  Note: There is some performance penalty associated with assembly bind failure logging.
1>  To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by ph1ll** [comment]
@CarlosFreire your problem is related to #44, setting the `WEBPROJ_ENABLEBETA7RENAMES` environment variable to `0` resolves this.

**Comment by CarlosFreire** [comment]
Thanks, I solved the issue

**Comment by emisaacson** [comment]
Is this related? This happens when trying to run or debug application in VS 2015 with dnx beta7 and beta7 packages (all up to date from nightly). I see some Microsoft.Framework.Runtime in the stack trace but the project compiles fine - this is a runtime error. Downgrading everything to beta6 runs fine.

    System.IO.FileLoadException: Could not load file or assembly '****.Application' or one of its dependencies. Invalid pointer (Exception from HRESULT: 0x80004003 (E_POINTER))
    File name: '****.Application' ---> System.ArgumentNullException: Value cannot be null.
    Parameter name: type
       at Microsoft.Framework.Runtime.Common.DependencyInjection.ActivatorUtilities.CreateFactory(Type type)
       at Microsoft.Framework.Runtime.Common.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider services, Type type)
       at Microsoft.Framework.Runtime.CompilerServices.CreateService[T](IServiceProvider sp, IAssemblyLoadContext loadContext, TypeInformation typeInfo)
       at Microsoft.Framework.Runtime.ProjectLibraryExportProvider.b__5_1(TypeInformation typeInfo)
       at System.Collections.Generic.DictionaryExtensions.GetOrAdd[TKey,TValue](IDictionary`2 dictionary, TKey key, Func`2 factory)
       at Microsoft.Framework.Runtime.ProjectLibraryExportProvider.<>c__DisplayClass5_0.b__0(CacheContext ctx)
       at Microsoft.Framework.Runtime.Caching.CacheExtensions.<>c__DisplayClass0_0`1.b__0(CacheContext ctx)
       at Microsoft.Framework.Runtime.Caching.Cache.CreateEntry(Object k, Func`2 acquire)
       at Microsoft.Framework.Runtime.Caching.Cache.<>c__DisplayClass5_0.b__0()
       at System.Lazy`1.CreateValue()
       at System.Lazy`1.LazyInitValue()
       at System.Lazy`1.get_Value()
       at Microsoft.Framework.Runtime.Caching.Cache.Get(Object key, Func`2 factory)
       at Microsoft.Framework.Runtime.Caching.CacheExtensions.Get[T](ICache cache, Object key, Func`2 factory)
       at Microsoft.Framework.Runtime.ProjectLibraryExportProvider.GetLibraryExport(CompilationTarget target)
       at Microsoft.Framework.Runtime.CompositeLibraryExportProvider.<>c__DisplayClass2_0.b__0(ILibraryExportProvider r)
       at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
       at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
       at Microsoft.Framework.Runtime.CompositeLibraryExportProvider.GetLibraryExport(CompilationTarget target)
       at Microsoft.Framework.Runtime.LibraryManager.GetLibraryExport(String name, String aspect)
       at Microsoft.Framework.Runtime.Loader.ProjectAssemblyLoader.Load(AssemblyName assemblyName, IAssemblyLoadContext loadContext)
       at Microsoft.Framework.Runtime.Loader.ProjectAssemblyLoader.Load(AssemblyName assemblyName)
       at dnx.host.LoaderContainer.Load(AssemblyName assemblyName)
       at dnx.host.DefaultLoadContext.LoadAssembly(AssemblyName assemblyName)
       at Microsoft.Framework.Runtime.Loader.AssemblyLoaderCache.GetOrAdd(AssemblyName name, Func`2 factory)
       at Microsoft.Framework.Runtime.Loader.LoadContext.LoadAssemblyImpl(AssemblyName assemblyName)
       at Microsoft.Framework.Runtime.Loader.LoadContext.TryLoadAssembly(LoadContext context, AssemblyName assemblyName, Assembly& assembly)
       at Microsoft.Framework.Runtime.Loader.LoadContext.ResolveAssembly(Object sender, ResolveEventArgs args)
       at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
       at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
       at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
       at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
       at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
       at Microsoft.AspNet.Hosting.Startup.StartupLoader.FindStartupType(String startupAssemblyName, IList`1 diagnosticMessages)
       at Microsoft.AspNet.Hosting.Internal.HostingEngine.EnsureStartup()
       at Microsoft.AspNet.Hosting.Internal.HostingEngine.EnsureApplicationServices()
       at Microsoft.AspNet.Hosting.Internal.HostingEngine.get_ApplicationServices()
       at Microsoft.AspNet.Loader.IIS.RuntimeHttpApplication.ApplicationStart(IHttpApplication application)
       at Microsoft.AspNet.Loader.IIS.HttpApplicationBase.InvokeApplicationStart(IHttpApplication application)

**Comment by CarlosFreire** [comment]
@emisaacson I have the same problem in VS 2015 with dnx beta7

**Comment by matthewDDennis** [comment]
I too have the problem when I upgraded to beta7-12264 and set  `EBPROJ_ENABLEBETA7RENAMES`

**Comment by anurse** [comment]
This is a known issue and there is a fix working it's way through our build process.

**Comment by endeffects** [comment]
Seems like the LibraryManager does not longer provide access to the LoadableAssemblies Collection in beta7, is it gone forever? I've used it for Dependency Injection in the past.

**Comment by davidfowl** [comment]
The property was renamed to Assemblies

**Comment by thangchung** [comment]
Thanks for this issue. It helps me a lot (y)

**Comment by selvaonline** [comment]
I am stil having the "Could not load file or assembly 'Microsoft.DNX.PackageManager" issue with beta8.

http://forums.asp.net/p/2077992/5991809.aspx?ASP+NET+5+Beta8+breaks+with+System+IO+FileNotFoundException+Could+not+load+file+or+assembly+Microsoft+DNX+PackageManager+or+one+of+its+dependencies+The+system+cannot+find+the+file+specified+1+File+name+Microsoft+DNX+PackageManager+

**Comment by Fosol** [comment]
Make sure you install the Visual Studio 2015 beta8 update.
https://www.microsoft.com/en-us/download/details.aspx?id=49442
